# .github/workflows/docker-publish.yml

name: Docker Image CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code from the repo
    - name: Checkout code
      uses: actions/checkout@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image
    - name: Build Docker image
      run: docker build -t your-dockerhub-username/your-repo-name:latest .

    # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push your-dockerhub-username/your-repo-name:latest
